In [1]:
import numpy as np
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [2]:
np.array([[1,2,3],(4,5,6),[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.array([1,2,3],dtype="float32")

array([1., 2., 3.], dtype=float32)

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.full((4,5),23)

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random()

0.8794122538024645

In [14]:
np.random.uniform(3)

2.047930153113368

In [16]:
np.random.random(size=3)

array([0.61524358, 0.55719788, 0.55535416])